baseURL = 'https://quantcodedenny.com/'
languageCode = 'en-us'
relativeURLs = true
canonifyURLs = true
title = "QuantCode: The Toolkit for Engineering-Driven Traders."
theme = "ananke"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
