baseURL = 'https://quantcodedenny.com/'
languageCode = 'en-us'
relativeURLs = true
canonifyURLs = true
title = "QuantCode: Use llm to improve your trading quality"
theme = "ananke"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
