baseURL = 'https://quantcodedenny.com/'
languageCode = 'en-us'
title = "Denny's personal experience for using llm as a pro for two things."
theme = "ananke"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
