baseURL = 'https://quantcodedenny.com/'
languageCode = 'en-us'
relativeURLs = true
canonifyURLs = true
title = "QuantCode: Use llm to improve your trading quality"
theme = "ananke"
enableRobotsTXT = true

[params]
  mainSections = ["posts"]

[pagination]
  pagerSize = 10
[menu]
  [[menu.main]]
    name = "Home"
    url = "/"
    weight = 10
  [[menu.main]]
    name = "About"
    url = "/posts/self-intro/"
    weight = 20
  [[menu.main]]
    name = "Leadership"
    url = "/tags/leadership/"
    weight = 50
  [[menu.main]]
    name = "Engineering"
    url = "/tags/engineering/"
    weight = 30
  [[menu.main]]
    name = "AI Trading"
    url = "/tags/trading-llm/"
    weight = 40
