baseURL = 'https://quantcodedenny.com/'
languageCode = 'en-us'
relativeURLs = true
canonifyURLs = true
title = "Denny - use llm as a pro for trade stock and infra engineering"
theme = "ananke"
enableRobotsTXT = true
[pagination]
  pagerSize = 10
