#+hugo_base_dir: ~/Dropbox/private_data/part_time/devops_blog/quantcodedenny.com
#+language: en
#+AUTHOR: dennyzhang
#+TAGS: Important(i) noexport(n)
#+HUGO_TAGS: trading
* Identify stock read flags                                        :noexport:

** prompt - buy the dip for QQQ                                     :noexport:
#+BEGIN_EXAMPLE
Create prompt to identify the dip for QQQ
#+END_EXAMPLE
** prompt - monitor HIMS stock                                     :noexport:
#+BEGIN_EXAMPLE
Evaluate the HIMS stock: ongoing trends, evaluations
#+END_EXAMPLE
** prompt - role setup                                             :noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: stock-role-setup
:EXPORT_DATE: 2025-08-25
:EXPORT_HUGO_SECTION: posts
:END:
You are a stock trading expert, specialized in high technology stocks
** prompt - create latest news                                     :noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: stock-create-latest-news
:EXPORT_DATE: 2025-08-25
:EXPORT_HUGO_SECTION: posts
:END:
#+BEGIN_EXAMPLE
Given a stock code, find all latest discussion for the past two weeks.

Find information from below sources
- X
- Facebook
- Reddit groups

Output:
- Generate a summary for the potential of this stock
- Highlight the latest news and progress
#+END_EXAMPLE
* prompt - monitor HIMS stock                                      :noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: monitor-hims-stock
:EXPORT_DATE: 2025-08-25
:EXPORT_HUGO_SECTION: posts
:END:
#+BEGIN_EXAMPLE
Evaluate the HIMS stock: ongoing trends, evaluations
#+END_EXAMPLE
* #  --8<-------------------------- separator ------------------------>8-- :noexport:
* prompt - role setup                                              :noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: stock-role-setup
:EXPORT_DATE: 2025-08-25
:EXPORT_HUGO_SECTION: posts
:END:
#+begin_example
You are a stock trading expert, specialized in high technology stocks
#+end_example
* prompt - buy the dip for QQQ                                     :noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: buy-dip-for-qqq
:EXPORT_DATE: 2025-08-25
:EXPORT_HUGO_SECTION: posts
:END:
#+BEGIN_EXAMPLE
Create prompt to identify the dip for QQQ
#+END_EXAMPLE
* prompt - create latest news                                      :noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: stock-create-latest-news
:EXPORT_DATE: 2025-08-25
:EXPORT_HUGO_SECTION: posts
:END:
#+BEGIN_EXAMPLE
Given a stock code, find all latest discussion for the past two weeks.

Find information from below sources
- X
- Facebook
- Reddit groups

Output:
- Generate a summary for the potential of this stock
- Highlight the latest news and progress
#+END_EXAMPLE
* Build and Reuse LLM Prompts to Decode High-Tech Stock Trends Fast. :noexport:
:PROPERTIES:
:EXPORT_FILE_NAME: llm-prompt-high-tech
:EXPORT_DATE: 2025-08-25
:EXPORT_HUGO_SECTION: posts
:END:

Analyze recent news and social media sentiment for {STOCK_TICKER} and summarize:
1. Overall sentiment (Bullish / Neutral / Bearish)
2. Top 3 reasons driving this sentiment
3. Suggested action for a long-term tech investor (watch / buy / sell)
Output as a concise bullet list.
* #  --8<-------------------------- separator ------------------------>8-- :noexport:
* TODO setup the blog prompt - Ask for P0 task with 2 hours size   :noexport:
Setup the context
You are a business strategist and product builder specializing in monetizing niche markets at the intersection of AI, finance, and engineering. Focus on LLM Quant for indie engineers/long-term traders. 

Ask for P0 task
I have 2 hours now. I want to create one reusable content or tool in this topic. What I shall work on?  I need one sentence statement. And the audience can understand and get attracte
d

* personal goal                                                    :noexport:
我想的目标就三个

1/ 避免常规的脑头一热：panic sell + fomo buy
2/ 找潜力股: 6个月前给我预警：open, hood, reddit, etc.
3/ 找龙头股的buy the dip： 上个月的unh
